In [1]:
import pandas as pd
import numpy as np

In [4]:
df1 = pd.read_excel("C:/Users/sim11/Desktop/JH/Bigdata/Project/Hanyang_Team4/Data/test1.xlsx",encoding='euc-kr')
print(df1.shape) #행 개수 및 열 개수 확인 (행의 경우 헤더부분 제외한 개수임)

(47035, 3)


In [11]:
df1.shape

(47035, 9)

In [5]:
df1.head()

단속일시  단속지역        단속장소
0  2019-08-04 11:30   개포동          14
1  2019-08-05 17:05   청담동          65
2  2019-08-04 09:52  대치4동      삼성로 부근
3  2019-08-04 13:16  삼성1동  봉은사로86길 부근
4  2019-08-04 14:38  일원1동      일원로 부근

In [6]:
df1['단속일시']=pd.to_datetime(df1['단속일시'])

In [7]:
df1['year']=df1['단속일시'].dt.year
df1['month']=df1['단속일시'].dt.month
df1['day']=df1['단속일시'].dt.day
df1['hour']=df1['단속일시'].dt.hour
df1['minute']=df1['단속일시'].dt.minute
df1['second']=df1['단속일시'].dt.second

In [9]:
df1.head()

단속일시  단속지역        단속장소  year  month  day  hour  minute  \
0 2019-08-04 11:30:00   개포동          14  2019      8    4    11      30   
1 2019-08-05 17:05:00   청담동          65  2019      8    5    17       5   
2 2019-08-04 09:52:00  대치4동      삼성로 부근  2019      8    4     9      52   
3 2019-08-04 13:16:00  삼성1동  봉은사로86길 부근  2019      8    4    13      16   
4 2019-08-04 14:38:00  일원1동      일원로 부근  2019      8    4    14      38   

   second  
0       0  
1       0  
2       0  
3       0  
4       0

In [10]:
df1['단속지역'].unique()

array(['개포동', '청담동', '대치4동', '삼성1동', '일원1동', '역삼동', '삼성동', '신사동', '논현동',
       '수서동', '세곡동', '대치동', '도곡1동', '논현1동', '자곡동', '도곡동', '삼성2동', '역삼1동',
       '논현2동', '대치2동', '개포2동', '일원동', '개포1동', '역삼2동', '압구정동', '대치1동',
       '율현동', '일원2동', '도곡2동', '개포4동', '일원본동'], dtype=object)

In [12]:
pd.options.display.max_columns=100

In [13]:
df2 = pd.read_csv("C:/Users/sim11/Desktop/JH/Bigdata/Project/Hanyang_Team4/Data/서울시 공영주차장 안내 정보.csv")
print(df2.shape) #행 개수, 열 개수 확인

(14505, 43)


In [14]:
df2.head()

주차장코드              주차장명                주소 주차장 종류 주차장 종류명  운영구분    운영구분명  \
0  1010089     초안산근린공원주차장(구)       도봉구 창동 24-0     NW  노외 주차장     1  시간제 주차장   
1  1012254   마들스타디움(근린공원)(구)     노원구 상계동 770-2     NW  노외 주차장     1  시간제 주차장   
2  1025695  영등포여자고등학교지하공영(구)    영등포구 신길동 184-3     NW  노외 주차장     1  시간제 주차장   
3  1025696     당산근린공원지하공영(구)  영등포구 당산동3가 385-0     NW  노외 주차장     1  시간제 주차장   
4  1025697          대림운동장(구)    영등포구 대림동 780-0     NW  노외 주차장     1  시간제 주차장   

           전화번호  주차현황 정보 제공여부                  주차현황 정보 제공여부명  \
0           NaN             0                           미연계중   
1  02-2289-6735             0                           미연계중   
2   02-831-6723             1  현재~20분이내 연계데이터 존재(현재 주차대수 표현)   
3  02-2633-0298             0                           미연계중   
4   02-831-3312             0                           미연계중   

   주차 면(주차 가능 차량 수)  현재 주차중인 대수     현재 주차 차량 업데이트 시간 유무료구분 유무료구분명 야간무료개방여부  \
0                68           0                  NaN     Y     유료        N   
1               177           0                  NaN     Y     유료        N   
2                98          92  2019-10-04 20:00:24     Y     유료        N   
3               190           0                  NaN     Y     유료        N   
4               192           0                  NaN     Y     유료        N   

  야간무료개방여부명  평일 운영 시작시각(HHMM)  평일 운영 종료시각(HHMM)  주말 운영 시작시각(HHMM)  \
0    야간 미개방               900              1900               900   
1    야간 미개방                 0              2400                 0   
2    야간 미개방              1000              1900              1000   
3    야간 미개방                 0              2400                 0   
4    야간 미개방               600              2200               600   

   주말 운영 종료시각(HHMM)  공휴일 운영 시작시각(HHMM)  공휴일 운영 종료시각(HHMM)  \
0              1900                900               1900   
1              2400                  0               2400   
2              1900               1000               1900   
3              2400                  0               2400   
4              2200                600               2200   

          최종데이터 동기화 시간 토요일 유,무료 구분 토요일 유,무료 구분명 공휴일 유,무료 구분 공휴일 유,무료 구분명  \
0  2019-06-10 09:33:08           N           무료           N           무료   
1  2019-06-10 09:36:13           N           무료           N           무료   
2  2019-06-10 09:33:16           N           무료           N           무료   
3  2019-06-10 09:33:47           N           무료           N           무료   
4  2019-06-10 09:33:47           N           무료           N           무료   

   월 정기권 금액 노상 주차장 관리그룹번호  기본 주차 요금  기본 주차 시간(분 단위)  추가 단위 요금  추가 단위 시간(분 단위)  \
0       0.0           NaN       0.0             NaN     300.0            10.0   
1  100000.0           NaN     150.0             5.0     150.0             5.0   
2   65000.0           NaN      50.0             5.0      50.0             5.0   
3  100000.0           NaN     150.0             5.0     150.0             5.0   
4   65000.0           NaN      50.0             5.0      50.0             5.0   

   버스 기본 주차 요금  버스 기본 주차 시간(분 단위)  버스 추가 단위 시간(분 단위)  버스 추가 단위 요금  일 최대 요금  \
0          0.0                0.0                0.0          0.0      0.0   
1          0.0                0.0                0.0          0.0  11000.0   
2          0.0                0.0                0.0          0.0      0.0   
3          0.0                0.0                0.0          0.0      0.0   
4          0.0                0.0                0.0          0.0      0.0   

   주차장 위치 좌표 위도  주차장 위치 좌표 경도   배정코드   배정코드명  
0     37.649279    127.040474  PIS02  미배정미점유  
1     37.643917    127.058567  PIS02  미배정미점유  
2     37.515205    126.915116  PIS02  미배정미점유  
3     37.525526    126.895794  PIS02  미배정미점유  
4     37.499657    126.894838  PIS02  미배정미점유

In [16]:
df2['주소'].unique() #이 데이터 같은 경우에는 unique 해서 보기에는 너무 많다 그래서 아래처럼

array(['도봉구 창동 24-0', '노원구 상계동 770-2', '영등포구 신길동 184-3',
       '영등포구 당산동3가 385-0', '영등포구 대림동 780-0', '서초구 양재동 23-0',
       '동대문구 휘경동 308-32', '동대문구 답십리동 23-3', '도봉구 방학동 632-1',
       '은평구 녹번동 153-1', '강남구 압구정동 428-0', '관악구 신림동 1456-3',
       '강남구 개포동 1273-0', '강북구 수유동 660-30', '강북구 미아동 860-123',
       '양천구 목동 919-8', '구로구 구로동 810-3', '노원구 상계동 373-13',
       '강남구 개포동 1266-0', '양천구 신정동 322-0', '중구 신당동 300-11',
       '중구 남산동2가 30-4', '노원구 중계동 26-0', '강남구 역삼동 829-20', '강남구 청담동 27-0',
       '강남구 삼성동 161-2', '강남구 논현동 168-0', '강남구 도곡동 922-0',
       '강남구 개포동 1204-0', '은평구 불광동 400-6', '은평구 신사동 193-0',
       '은평구 진관동 66-30', '성동구 사근동 104-0', '성동구 응봉동 3-11', '성동구 마장동 525-0',
       '강서구 화곡동 98-99', '동작구 사당동 1046-1', '동작구 동작동 326-0',
       '관악구 신림동 511-1', '성북구 정릉동 865-7', '성북구 하월곡동 104-112',
       '서초구 잠원동 10-33', '서초구 반포동 5-1', '서초구 반포동 95-13', '서초구 신원동 224-3',
       '동대문구 용두동 8-1', '동대문구 신설동 114-29', '강동구 천호동 457-7',
       '광진구 구의동 219-15', '광진구 군자동 374-7', '강동구 암사동 59-2', '마포구 공덕

In [10]:
df2['주소'].value_counts() # 값 마다의 개수 확인

성동구 용답동 225-13     332
강서구 화곡동 914-3      299
성동구 성수동2가 276-5    282
강남구 율현동 101-10     244
강서구 화곡동 881-14     209
                  ... 
서초구 양재동 90-2         1
금천구 가산동 148-28       1
강북구 미아동 4-1          1
중구 다동 39-3           1
서초구 반포동 730-0        1
Name: 주소, Length: 884, dtype: int64

In [20]:
df2['구']=df2['주소'].str.split(' ', expand=True)[0]
df2['구'].value_counts()

강남구     1468
중구      1353
영등포구    1351
강서구     1219
성동구     1125
양천구      894
마포구      751
동대문구     690
금천구      657
중랑구      650
종로구      643
노원구      630
송파구      522
강북구      459
관악구      355
서초구      334
광진구      325
용산구      253
구로구      243
강동구      150
동작구      140
서대문구     128
도봉구       78
성북구       61
은평구       26
Name: 구, dtype: int64

In [21]:
df2['동']=df2['주소'].str.split(' ', expand=True)[1]
df2['동'].value_counts()

화곡동      946
여의도동     754
신정동      487
상계동      448
대치동      418
가산동      418
서교동      372
마장동      360
용답동      334
신림동      302
성수동2가    301
제기동      298
수유동      284
방배동      269
신월동      246
율현동      245
독산동      231
삼성동      204
인현동2가    204
망우동      197
묵동       196
압구정동     194
미아동      170
목동       161
자양동      159
을지로3가    146
중계동      144
효창동      143
종로6가     138
중화동      129
        ... 
거여동        1
명륜3가       1
암사동        1
세곡동        1
마포동        1
삼전동        1
갈현동        1
신수동        1
대방동        1
광장동        1
군자동        1
원지동        1
영등포동       1
홍은동        1
중림동        1
잠원동        1
서빙고동       1
필동3가       1
하월곡동       1
적선동        1
서린동        1
훈정동        1
당산동        1
서계동        1
삼선동3가      1
녹번동        1
신원동        1
필동2가       1
충무로5가      1
미근동        1
Name: 동, Length: 264, dtype: int64

In [22]:
gangnam = df2[df2['구'].str.contains('강남')]
gangnam.shape

(1468, 45)

In [26]:
df2[df2['구'].str.contains('강남')].shape

(1468, 45)

In [14]:
gangnam.columns

Index(['주차장코드', '주차장명', '주소', '주차장 종류', '주차장 종류명', '운영구분', '운영구분명', '전화번호',
       '주차현황 정보 제공여부', '주차현황 정보 제공여부명', '주차 면(주차 가능 차량 수)', '현재 주차중인 대수',
       '현재 주차 차량 업데이트 시간', '유무료구분', '유무료구분명', '야간무료개방여부', '야간무료개방여부명',
       '평일 운영 시작시각(HHMM)', '평일 운영 종료시각(HHMM)', '주말 운영 시작시각(HHMM)',
       '주말 운영 종료시각(HHMM)', '공휴일 운영 시작시각(HHMM)', '공휴일 운영 종료시각(HHMM)',
       '최종데이터 동기화 시간', '토요일 유,무료 구분', '토요일 유,무료 구분명', '공휴일 유,무료 구분',
       '공휴일 유,무료 구분명', '월 정기권 금액', '노상 주차장 관리그룹번호', '기본 주차 요금',
       '기본 주차 시간(분 단위)', '추가 단위 요금', '추가 단위 시간(분 단위)', '버스 기본 주차 요금',
       '버스 기본 주차 시간(분 단위)', '버스 추가 단위 시간(분 단위)', '버스 추가 단위 요금', '일 최대 요금',
       '주차장 위치 좌표 위도', '주차장 위치 좌표 경도', '배정코드', '배정코드명', '구', '동'],
      dtype='object')

In [27]:
df1.head()

단속일시  단속지역        단속장소  year  month  day  hour  minute  \
0 2019-08-04 11:30:00   개포동          14  2019      8    4    11      30   
1 2019-08-05 17:05:00   청담동          65  2019      8    5    17       5   
2 2019-08-04 09:52:00  대치4동      삼성로 부근  2019      8    4     9      52   
3 2019-08-04 13:16:00  삼성1동  봉은사로86길 부근  2019      8    4    13      16   
4 2019-08-04 14:38:00  일원1동      일원로 부근  2019      8    4    14      38   

   second  
0       0  
1       0  
2       0  
3       0  
4       0

In [28]:
df1['단속지역'].value_counts()

역삼동     9673
논현동     6834
대치동     5311
청담동     4519
신사동     4271
삼성동     3149
수서동     1759
개포동     1156
일원동     1127
논현2동    1118
삼성2동    1013
도곡동      997
역삼1동     953
세곡동      879
대치2동     691
압구정동     624
자곡동      570
대치4동     520
삼성1동     511
논현1동     345
율현동      225
도곡1동     214
대치1동     169
역삼2동     140
일원2동     109
일원1동      83
도곡2동      32
개포2동      31
개포4동       7
개포1동       4
일원본동       1
Name: 단속지역, dtype: int64

In [29]:
gangnam['동'].value_counts()

대치동     418
율현동     245
삼성동     204
압구정동    194
신사동     115
도곡동      72
개포동      71
청담동      51
논현동      46
일원동      33
역삼동      16
수서동       2
세곡동       1
Name: 동, dtype: int64

In [30]:
a=pd.DataFrame(df1['단속지역'].value_counts())
a=a.rename({'단속지역':'단속건수'},axis=1)
a.head()

단속건수
역삼동  9673
논현동  6834
대치동  5311
청담동  4519
신사동  4271

In [31]:
b=pd.DataFrame(gangnam['동'].value_counts())
b=b.rename({'동':'주차장수'},axis=1)
b.head()

주차장수
대치동    418
율현동    245
삼성동    204
압구정동   194
신사동    115

In [20]:
print(a.shape,b.shape)

(31, 1) (13, 1)


In [32]:
new_train=pd.concat([a,b],sort=False,axis=1)
print(new_train.shape)
new_train.head()

(31, 2)


단속건수   주차장수
역삼동  9673   16.0
논현동  6834   46.0
대치동  5311  418.0
청담동  4519   51.0
신사동  4271  115.0

In [33]:
new_train.index.names = ['동']
new_train=new_train.reset_index()

In [34]:
new_train.head()

동  단속건수   주차장수
0  역삼동  9673   16.0
1  논현동  6834   46.0
2  대치동  5311  418.0
3  청담동  4519   51.0
4  신사동  4271  115.0

In [35]:
new_train.tail()

동  단속건수  주차장수
26  도곡2동    32   NaN
27  개포2동    31   NaN
28  개포4동     7   NaN
29  개포1동     4   NaN
30  일원본동     1   NaN

In [25]:
df1['단속지역'].unique()

array(['개포동', '청담동', '대치4동', '삼성1동', '일원1동', '역삼동', '삼성동', '신사동', '논현동',
       '수서동', '세곡동', '대치동', '도곡1동', '논현1동', '자곡동', '도곡동', '삼성2동', '역삼1동',
       '논현2동', '대치2동', '개포2동', '일원동', '개포1동', '역삼2동', '압구정동', '대치1동',
       '율현동', '일원2동', '도곡2동', '개포4동', '일원본동'], dtype=object)

In [26]:
gangnam['동'].unique()  

array(['압구정동', '개포동', '역삼동', '청담동', '삼성동', '논현동', '도곡동', '일원동', '대치동',
       '수서동', '신사동', '율현동', '세곡동'], dtype=object)

In [27]:
def add_func(data):
    data = str(data)
    
    if "개포" in data:
        return "개포동"
    elif "청담" in data:
        return "청담동"
    elif "대치" in data:
        return "대치동"
    elif "삼성" in data:
        return "삼성동"
    elif "일원" in data:
        return "일원동"
    elif "논현" in data:
        return "논현동"
    elif "도곡" in data:
        return "도곡동"
    elif "역삼" in data:
        return "역삼동"
    elif "신사" in data:
        return "신사동"
    elif "수서" in data:
        return "수서동"
    elif "세곡" in data:
        return "세곡동"
    elif "자곡" in data:
        return "자곡동"
    elif "율현" in data:
        return "율현동"
    else:
        return "압구정동"


In [28]:
df1['단속지역']=df1['단속지역'].apply(add_func)

In [29]:
df1['단속지역'].unique()

array(['개포동', '청담동', '대치동', '삼성동', '일원동', '역삼동', '신사동', '논현동', '수서동',
       '세곡동', '도곡동', '자곡동', '압구정동', '율현동'], dtype=object)

In [30]:
gangnam['동'].unique()  

array(['압구정동', '개포동', '역삼동', '청담동', '삼성동', '논현동', '도곡동', '일원동', '대치동',
       '수서동', '신사동', '율현동', '세곡동'], dtype=object)

In [31]:
len(df1['단속지역'].unique())  #자곡동...

14

In [32]:
len(gangnam['동'].unique()  )

13

In [33]:
a=pd.DataFrame(df1['단속지역'].value_counts())
a=a.rename({'단속지역':'단속건수'},axis=1)
a.head()


단속건수
역삼동  10766
논현동   8297
대치동   6691
삼성동   4673
청담동   4519

In [34]:
b=pd.DataFrame(gangnam['동'].value_counts())
b=b.rename({'동':'주차장수'},axis=1)
b.head()


주차장수
대치동    418
율현동    245
삼성동    204
압구정동   194
신사동    115

In [35]:
new_train=pd.concat([a,b],sort=False,axis=1)
print(new_train.shape)
new_train.head()



(14, 2)


단속건수   주차장수
역삼동  10766   16.0
논현동   8297   46.0
대치동   6691  418.0
삼성동   4673  204.0
청담동   4519   51.0

In [36]:
new_train.index.names = ['동']
new_train=new_train.reset_index()

new_train.head()

동   단속건수   주차장수
0  역삼동  10766   16.0
1  논현동   8297   46.0
2  대치동   6691  418.0
3  삼성동   4673  204.0
4  청담동   4519   51.0

In [37]:
new_train.tail() #자곡동 주차장수 없음

동  단속건수   주차장수
9    개포동  1198   71.0
10   세곡동   879    1.0
11  압구정동   624  194.0
12   자곡동   570    NaN
13   율현동   225  245.0

In [36]:
new_train.head(14)

동  단속건수   주차장수
0    역삼동  9673   16.0
1    논현동  6834   46.0
2    대치동  5311  418.0
3    청담동  4519   51.0
4    신사동  4271  115.0
5    삼성동  3149  204.0
6    수서동  1759    2.0
7    개포동  1156   71.0
8    일원동  1127   33.0
9   논현2동  1118    NaN
10  삼성2동  1013    NaN
11   도곡동   997   72.0
12  역삼1동   953    NaN
13   세곡동   879    1.0

In [37]:
result_save = new_train.to_csv("C:/Users/sim11/Desktop/JH/Bigdata/Project/Hanyang_Team4/Data/04.new_train.csv", encoding='euc_kr')

In [39]:
df3 = pd.read_csv("C:/Users/sim11/Desktop/JH/Bigdata/Project/Hanyang_Team4/Data/04.new_train.csv",encoding='euc-kr')

In [40]:
df3

Unnamed: 0     동  단속건수   주차장수
0            0   역삼동  9673   16.0
1            1   논현동  6834   46.0
2            2   대치동  5311  418.0
3            3   청담동  4519   51.0
4            4   신사동  4271  115.0
5            5   삼성동  3149  204.0
6            6   수서동  1759    2.0
7            7   개포동  1156   71.0
8            8   일원동  1127   33.0
9            9   도곡동   997   72.0
10          10   세곡동   879    1.0
11          11  압구정동   624  194.0
12          12   자곡동   570    NaN
13          13   율현동   225  245.0

In [41]:
np.corrcoef(df3['단속건수'],df3['주차장수'])

array([[ 1., nan],
       [nan, nan]])

In [42]:
df3.at[12,"주차장수"] = 0

In [43]:
df3

Unnamed: 0     동  단속건수   주차장수
0            0   역삼동  9673   16.0
1            1   논현동  6834   46.0
2            2   대치동  5311  418.0
3            3   청담동  4519   51.0
4            4   신사동  4271  115.0
5            5   삼성동  3149  204.0
6            6   수서동  1759    2.0
7            7   개포동  1156   71.0
8            8   일원동  1127   33.0
9            9   도곡동   997   72.0
10          10   세곡동   879    1.0
11          11  압구정동   624  194.0
12          12   자곡동   570    0.0
13          13   율현동   225  245.0

In [44]:
np.corrcoef(df3['단속건수'],df3['주차장수'])

array([[1.        , 0.02599335],
       [0.02599335, 1.        ]])

In [45]:
from sklearn import preprocessing

In [47]:
col = ["단속건수","주차장수"]
x = df3[col].values
x

array([[9.673e+03, 1.600e+01],
       [6.834e+03, 4.600e+01],
       [5.311e+03, 4.180e+02],
       [4.519e+03, 5.100e+01],
       [4.271e+03, 1.150e+02],
       [3.149e+03, 2.040e+02],
       [1.759e+03, 2.000e+00],
       [1.156e+03, 7.100e+01],
       [1.127e+03, 3.300e+01],
       [9.970e+02, 7.200e+01],
       [8.790e+02, 1.000e+00],
       [6.240e+02, 1.940e+02],
       [5.700e+02, 0.000e+00],
       [2.250e+02, 2.450e+02]])

In [49]:
min_max_scaler = preprocessing.MinMaxScaler()

In [51]:
x_scaled = min_max_scaler.fit_transform(x.astype(float))

In [52]:
x_scaled

array([[1.        , 0.03827751],
       [0.69951312, 0.11004785],
       [0.53831499, 1.        ],
       [0.45448772, 0.12200957],
       [0.42823878, 0.27511962],
       [0.30948349, 0.48803828],
       [0.1623624 , 0.00478469],
       [0.09853937, 0.16985646],
       [0.09546994, 0.07894737],
       [0.08171041, 0.1722488 ],
       [0.069221  , 0.00239234],
       [0.04223116, 0.46411483],
       [0.03651566, 0.        ],
       [0.        , 0.5861244 ]])

In [54]:
df4 = pd.DataFrame(x_scaled, columns = col, index=df3.index)

In [55]:
df4

단속건수      주차장수
0   1.000000  0.038278
1   0.699513  0.110048
2   0.538315  1.000000
3   0.454488  0.122010
4   0.428239  0.275120
5   0.309483  0.488038
6   0.162362  0.004785
7   0.098539  0.169856
8   0.095470  0.078947
9   0.081710  0.172249
10  0.069221  0.002392
11  0.042231  0.464115
12  0.036516  0.000000
13  0.000000  0.586124

In [56]:
np.corrcoef(df4['단속건수'],df4['주차장수'])

array([[1.        , 0.02599335],
       [0.02599335, 1.        ]])